ARG BAY_IMAGE_VERSION=latest

# @see https://github.com/dpc-sdp/bay/blob/master/bay/images/Dockerfile.php
FROM singledigital/bay-cli:${BAY_IMAGE_VERSION}

ENV DRUPAL_MODULE_PREFIX=%%DRUPAL_MODULE_PREFIX%%

ADD patches /app/patches
ADD scripts /app/scripts
ADD dpc-sdp /app/dpc-sdp

COPY composer.json composer.lock auth.json .env /app/

ENV COMPOSER_MEMORY_LIMIT=-1
RUN composer install -n --no-dev --ansi --prefer-dist --no-suggest --optimize-autoloader && composer clearcache

COPY . /app
