# Docker Compose configuration file.
#
# - Using a single file to work in local, CI and production environments.
# - Local overrides are possible using docker-composer.override.yml file.
# - Use inline comments starting with ### to have the line removed in CI.
version: '2.3'

x-bay-image-version:
  &bay-image-version ${BAY_IMAGE_VERSION:-latest}

x-project:
  &project ${PROJECT_NAME:-mysite}

x-volumes:
  &default-volumes
  # Understanding host mounting in Docker-based projects.
  #
  # To share application code between services (containers), Docker uses volumes.
  # When used in non-development environments, containers have access to
  # the same shared files using volumes and these volumes do not need to be
  # mounted from the host. But for development environment, when the code
  # constantly changes on the host, we need to have these changes synchronized
  # into all containers. Since we are using single `docker-compose.yml` file for
  # all environments, we have to accommodate both cases, so we are specifying an
  # override for the same directory as a mounted volume as a commented-out lines,
  # which will be automatically uncommented in CI.
  #
  # See Docker Compose reference about volumes https://docs.docker.com/compose/compose-file/compose-file-v2/#volume-configuration-reference
  volumes:
    - .:/app:${VOLUME_FLAGS:-delegated} ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
    - ./docroot/sites/default/files:/app/docroot/sites/default/files:${VOLUME_FLAGS:-delegated} ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
    ##- app:/app
    ##- files:/app/docroot/sites/default/files

x-environment:
  &default-environment
  LAGOON_PROJECT: *project
  # Local dev URL populated from the environment. Do not override here. Instead,
  # specify the value in .env file.
  LAGOON_LOCALDEV_URL: ${LOCALDEV_URL:-http://mysite.docker.amazee.io}
  LAGOON_ROUTE: ${LOCALDEV_URL:-http://mysite.docker.amazee.io}
  GITHUB_TOKEN: ${GITHUB_TOKEN:-}
  BAY_KEY: ${BAY_KEY:-}
  BAY_IMAGE_VERSION: ${BAY_IMAGE_VERSION:-latest}
  LAGOON_ENVIRONMENT_TYPE: ${LAGOON_ENVIRONMENT_TYPE:-local}
  DRUPAL_REFRESH_SEARCHAPI: ${DRUPAL_REFRESH_SEARCHAPI:-}
  AUTHENTICATED_CONTENT: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAqplMy0/I1ThEf/jo/oqpOr4HG5+wq4gPoL5bDTKTMODs89TU
    yuzDVNNPyRg2SVBIIanbAlCiUE4xLc7c89nCGkhCC2117ZFUQY/nlyL+xOZqT1Gf
    PmnX0pRngMqeM3LmikiqwObEVjQkcHuX65/u0ZBgxxMTW/bhNygV4I+ijNtBXd2B
    eN3qjVkJ2lVidB+J8YJ3p5rNMvN3/mdiBjOy3TBC7ZsWyQ6A9xRVAczCakFSFjh/
    6hjL4yb0llKbPIxrWjPfvgHtQpHid1hapQ8IJKRsfmbB+K6eOP/buxUxSPlNNVa8
    UaKSYm1MdL8JWhKTqujIsvjlfizQv1b1UBRGrwIDAQABAoIBACm1l0/x7sEqo5zC
    J3zsO9nP0f8P+OrHNkLvp2U/ozsFEwm+VFRUtKENlOkukT81cJ1CYPhc7IJDy8RO
    WjkIWWuBlRwkI/v0Vyw8Wbva430SdJV1+EATMqAahn+3ihw8EF9oys6k3QXSc8JI
    hWknTgVQjki9wjLu1jtdApRHqc9T+aMT4jeIy7ZpE2vtE2pT+XOw25bdVggz0Zb5
    6wCCtwRIeopwdnlERpYd8nE6NO/oKPHp1lz/RHKtYCVm9CNdBfpvgzKPMB1L3h7O
    kvxsBmxGYX+eQtEd8qVUDjDzsIRALwBoIzTEERK6ueiAC3CNip3rKx7FPdPwHFig
    Y3+2teECgYEA0s4xRNJvQM5CKRONtb1gnxIRoQS0jsjTDpG1LMpLQl+cXRbYo+WW
    N16pWtiUAN29SOai28GM+pze44trMZlaoEkGjhWAnOPbqDzZRbAIgSdqmVjCkmqK
    a7VyqDBxyy688fxCKejt0zNxEwlKQi2HhPaECHqUGweKxug3ms7pXR8CgYEAzyxq
    R22NyEqOZ6eRooev6yZXhr1XsshcjXzvyKWySOpbgG8Zu5KIwxxEjzlVCGOlHFdW
    wFAD7PrG4Q0XWeEJ/S4B+qmBaj654Sln5woI/YCDJaLv5NtIQuLLoZtysX/CNThb
    8o9yLE9XifC8wWmn2GhIS46VguIozNgeBoL8VHECgYAzphNKMmjRrvdkywaoZYrb
    zniFQ/rdFPUpF6gVHkdMLtLHuAZCOckRLd8+g9vXTnzG9MMoJobdDDxL8efEkjcz
    GFFD1J7bUbSKxsXRHi0nP7oNckLRzsq1UxKRhLUMvBnNDCpFzG0glvT4XglUp4UR
    nbiBv060RKfKzjB5fIKOrwKBgH5z+8LxabMxXs6CB3CPJZ+AXbhOZfMoPOXXtnxg
    Nvwun/860Rgejv+Yh3hsZCyktakg3kCwFlVVlILVfMVNiM1Sgb7AK8/vzYFTxqnN
    BEPHZ0VXuNmVxvucdvKDcXRKKP5XEjhxuhy1qRb3LB9aICsFK+uCclvbM1AlMd6D
    oQThAoGBALqCpR4Zo/I0vvEfhMzoJqpwoJTISWtJyp2htwlHq1+X9NdsEEcrWBRQ
    VV06ctOexEcieMpzoT3n/4EThNG+7TPyjtAnyeRtqdgiA/oXeP5HP/npYam56KeA
    B21Ae3qNj0KwSqvIpwLlvkxu+lW2nWyeor2AXKJWEdm3ZImJICum
    -----END RSA PRIVATE KEY-----
  # Uncomment to enable Xdebug and then restart via `ahoy up`.
  #XDEBUG_ENABLE: "true"

services:

  cli:
    build:
      context: .
      dockerfile: .docker/Dockerfile.cli
      args:
        COMPOSER: ${COMPOSER:-composer.json}
        BAY_IMAGE_VERSION: *bay-image-version
    image: *project
    environment:
      << : *default-environment
    << : *default-volumes
    volumes_from: ### Local overrides to mount host SSH keys. Automatically removed in CI.
      - container:amazeeio-ssh-agent ### Local overrides to mount host SSH keys. Automatically removed in CI.
    labels:
      lagoon.type: cli-persistent
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.persistent.name: nginx-php

  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile.nginx-drupal
      args:
        CLI_IMAGE: *project
        BAY_IMAGE_VERSION: *bay-image-version
    << : *default-volumes
    environment:
      << : *default-environment
    depends_on:
      - cli
    networks:
      - amazeeio-network
      - default
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.persistent.class: slow
      lagoon.name: nginx-php
    expose:
    - "8080"
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php
      args:
        CLI_IMAGE: *project
        BAY_IMAGE_VERSION: *bay-image-version
    environment:
      << : *default-environment
    << : *default-volumes
    depends_on:
      - cli
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.persistent.class: slow
      lagoon.name: nginx-php

  mariadb:
    image: amazeeio/mariadb-drupal
    environment:
      << : *default-environment
    ports:
    - "3306" # Find port on host with `ahoy info` or `docker-compose port mariadb 3306`
    labels:
      lagoon.type: mariadb-shared

  redis:
    image: amazeeio/redis
    labels:
      lagoon.type: redis

  elasticsearch:
    build:
      context: .
      dockerfile: .docker/Dockerfile.elasticsearch
      args:
      - ES_TPL=${ES_TPL:-elasticsearch.yml}
    labels:
      lagoon.type: none

  chrome:
    image: selenium/standalone-chrome
    shm_size: '1gb'
    environment:
      << : *default-environment
    << : *default-volumes
    depends_on:
      - cli
    labels:
      lagoon.type: none

networks:
  amazeeio-network:
    external: true

volumes:
  app: {}
  files: {}
