version: 2
aliases:

  # Fingerprint of the SSH deploy key of the project used to pull code.
  # The value can be found in CircleCI UI -> SSH Permissions.
  - &ssh_key_fingerprint "36:03:e3:ca:b3:0b:82:18:e2:e9:ae:5d:81:17:86:b1"

  - &step_configure_git
    run:
      name: Configure git
      command: |
        git config --global user.email "$DEPLOY_USER_EMAIL" && git config --global user.name "$DEPLOY_USER_NAME"

  # Re-usable job to run different types of builds.
  - &job-build
    working_directory: &working-directory /app
    docker:
      - image: &builder-image integratedexperts/ci-builder
        environment:
          SSH_KEY_FINGERPRINT: *ssh_key_fingerprint
          LAGOON_ENVIRONMENT_TYPE: ci
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Add GitHub token into container environment variable
          command: |
            echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
      - add_ssh_keys:
          fingerprints:
            - *ssh_key_fingerprint
      - run:
          name: Add SSH key into container environment variable
          command: |
            SSH_KEY_FILE="${SSH_KEY_FINGERPRINT//:}" && SSH_KEY_FILE="id_rsa_${SSH_KEY_FILE//\"}" && export $SSH_KEY_FILE
            cp ~/.ssh/$SSH_KEY_FILE /app/bay_key
      - run:
          name: Run build script
          command: |
            .circleci/build.sh
      - run: .circleci/test.sh
      - run:
          name: Copy artifacts
          command: .circleci/test-artifacts.sh
          when: always
      - store_artifacts:
          path: /tmp/artifacts

  # Job to perform a partial build and export config.
  - &job-export-config
    working_directory: *working-directory
    docker:
      - image: *builder-image
        environment:
          LAGOON_ENVIRONMENT_TYPE: ci
          SSH_KEY_FINGERPRINT: *ssh_key_fingerprint
          DEPLOY_USER_EMAIL: sdp.devs@dpc.vic.gov.au
          DEPLOY_USER_NAME: sdpdeploy
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - *step_configure_git
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - *ssh_key_fingerprint
      - run:
          name: Add SSH key into container environment variable
          command: |
            SSH_KEY_FILE="${SSH_KEY_FINGERPRINT//:}" && SSH_KEY_FILE="id_rsa_${SSH_KEY_FILE//\"}" && export $SSH_KEY_FILE
            cp ~/.ssh/$SSH_KEY_FILE /app/bay_key
      - run:
          name: Install site and export config
          command: .circleci/export-config.sh

jobs:
  export-config:
    <<: *job-export-config

  build:
    <<: *job-build

workflows:
  version: 2
  main:
    jobs:
      - export-config:
          filters:
            branches:
              only: /^automation\/.*/
      - build:
          filters:
            branches:
              ignore: /api|api\-edge|^automation\/.*/
