version: 2
aliases:

  # Fingerprint of the SSH deploy key of the project used to pull code.
  # The value can be found in CircleCI UI -> SSH Permissions.
  - &deploy_ssh_fingerprint "60:10:9b:99:11:cc:c1:99:97:3e:f4:66:ca:d1:96:58"

  # Fingerprint of the SSH key for the machine user used to push code into repositories.
  # The value can be found in CircleCI UI -> SSH Permissions.
  - &user_ssh_fingerprint "bd:ac:32:00:c6:1b:79:e6:00:a2:e8:0c:21:2e:b9:ff"

  - &step_configure_git
    run:
      name: Configure git
      command: |
        git config --global user.email "$DEPLOY_USER_EMAIL" && git config --global user.name "$DEPLOY_USER_NAME"

  # Re-usable job to run different types of builds.
  - &job-build
    working_directory: &working-directory /app
    docker:
      - image: &builder-image integratedexperts/ci-builder
        environment:
          SSH_KEY_FINGERPRINT: *deploy_ssh_fingerprint
          LAGOON_ENVIRONMENT_TYPE: ci
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - run: ./dev-tools.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Add GitHub token into container environment variable
          command: |
            echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
      - run:
          name: Run build script
          command: |
            .circleci/build.sh
      - run: .circleci/test.sh
      - run:
          name: Copy artifacts
          command: .circleci/test-artifacts.sh
          when: always
      - store_artifacts:
          path: /tmp/artifacts

  # Re-usable job to mirror code.
  - &job-mirror
    working_directory: *working-directory
    docker:
      - image: *builder-image
    environment:
      DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - *step_configure_git
      - run: ./dev-tools.sh
      - run: .circleci/mirror.sh

  # Job to perform a partial build and export config.
  - &job-export-config
    working_directory: *working-directory
    docker:
      - image: *builder-image
        environment:
          LAGOON_ENVIRONMENT_TYPE: ci
          DEPLOY_USER_EMAIL: sdp.devs@dpc.vic.gov.au
          DEPLOY_USER_NAME: sdpdeploy
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - *step_configure_git
      - run: ./dev-tools.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - *user_ssh_fingerprint
      - run:
          name: Install site and export config
          command: .circleci/export-config.sh

jobs:
  export-config:
    <<: *job-export-config

  build:
    <<: *job-build

  build-install:
    <<: *job-build
    docker:
      - image: *builder-image
        environment:
          SSH_KEY_FINGERPRINT: *deploy_ssh_fingerprint
          LAGOON_ENVIRONMENT_TYPE: ci
          INSTALL_NEW_SITE: 1
          BEHAT_PROFILE: "--profile=tide"

  push-api:
    <<: *job-mirror
    docker:
      - image: *builder-image
        environment:
          MIRROR_GIT_BRANCH: api

  push-api-edge:
    <<: *job-mirror
    docker:
      - image: *builder-image
        environment:
          MIRROR_GIT_BRANCH: api-edge

workflows:
  version: 2
  main:
    jobs:
      - export-config:
          filters:
            branches:
              only: ^automation\/
      - build-install:
          filters:
            branches:
              ignore: /api|api\-edge|^automation\/.*/
      - build:
          filters:
            branches:
              ignore: /api|api\-edge|^automation\/.*/
      - push-api:
          requires:
            - build-install
          filters:
            branches:
              only: master
      - push-api-edge:
          requires:
            - build-install
          filters:
            branches:
              only: /develop|ci/
